name: Push Docker image
on:
  push:
    tags:
      - v0.*
      - v1.*
      - v2.*


jobs:
  build:

    # Permissions for GITHUB_TOKEN
    permissions:
      contents: read  # To check out repo
      packages: write # To read NPM registry and push Docker image

    uses: gunet/wallet-ecosystem/.github/workflows/docker-build-push.yml@dc4eu-rome
    secrets: inherit
    with:
      image-tag: ghcr.io/gunet/wallet-enterprise:${{ github.ref_name }}
      docker-push: true
      dockerfile-path: ./Dockerfile
