name: Push Docker image
on:
  push:
    tags:
      - v0.*
      - v1.*
      - v2.*


jobs:
  push-base:
    # Permissions for GITHUB_TOKEN
    permissions:
      contents: read  # To check out repo
      packages: write  # To read NPM registry

    uses: wwwallet/wallet-ecosystem/.github/workflows/docker-build-push.yml@master
    secrets: inherit
    with:
      image-tag: ghcr.io/wwwallet/wallet-enterprise:base
      docker-push: true
      dockerfile-path: ./base.Dockerfile