name: Build and push Docker image

on:
  push:
    branches:
      - dc-workflow

jobs:
  build:

    # Permissions for GITHUB_TOKEN
    permissions:
      contents: read  # To check out repo
      packages: write # To read NPM registry and push Docker image

    uses: gunet/wallet-ecosystem/.github/workflows/docker-build-push.yml@dc4eu-rome
    with:
      image-tag: ghcr.io/gunet/wallet-enterprise:latest
      docker-push: true
