name: Build Docker image

on:
  push:
    branches-ignore:
      - master
  pull_request:

jobs:
  build-base:
    # Permissions for GITHUB_TOKEN
    permissions:
      contents: read  # To check out repo
      packages: read  # To read NPM registry

    uses: wwwallet/wallet-ecosystem/.github/workflows/docker-build-push.yml@master
    secrets: inherit
    with:
      image-tag: ghcr.io/wwwallet/wallet-enterprise:base
      docker-push: false
      dockerfile-path: ./base.Dockerfile