name: Build Docker image

on:
  push:
    branches-ignore:
      - master  # Covered by docker-push.yml
      - dc4eu-rome
  pull_request:

jobs:
  build:

    # Permissions for GITHUB_TOKEN
    permissions:
      contents: read  # To check out repo
      packages: read  # To read NPM registry

    uses: gunet/wallet-ecosystem/.github/workflows/docker-build-push.yml@dc4eu-rome
    secrets: inherit
    with:
      image-tag: ghcr.io/gunet/wallet-enterprise:latest
      docker-push: false
      dockerfile-path: ./Dockerfile
