name: Build Docker image

on:
  push:
    branches-ignore:
      - dc-workflow  # Covered by docker-push.yml
  pull_request:

jobs:
  build:

    # Permissions for GITHUB_TOKEN
    permissions:
      contents: read  # To check out repo
      packages: read  # To read NPM registry

    uses: gunet/wallet-ecosystem/.github/workflows/docker-build-push.yml@dc-workflow
    with:
      image-tag: ghcr.io/gunet/wallet-enterprise:base
      docker-push: false
      dockerfile-path: ./base.Dockerfile

